// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvakpupzkvrpevqxtywy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2YWtwdXB6a3ZycGV2cXh0eXd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjgwMTgsImV4cCI6MjA2NTUwNDAxOH0.366-EVTERDtGFjBzHQ3jFiFGNSu9E21haBAnV83dP1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);